apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: messaging-app
  template:
    metadata:
      labels:
        app: messaging-app
    spec:
      containers:
        - name: messaging-app-container
          image: your-dockerhub-username/messaging_app_image:latest # 🔥 Replace with your image
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_DB_HOST
              value: "mysql-service"
            - name: DJANGO_DB_NAME
              value: "messaging_db"
            - name: DJANGO_DB_USER
              value: "messaging_user"
            - name: DJANGO_DB_PASSWORD
              value: "messaging_password"
