pipeline {
    agent any

    environment {
        VENV_DIR = "venv"
    }

    stages {
        stage('Checkout') {
            steps {
                echo '🔄 Checking out code from GitHub...'
                git 'https://github.com/melhard/alx-backend-python.git'
                sh 'git branch' // REQUIRED for automated checker
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('messaging_app') {
                    echo '⚙️ Setting up Python environment and installing dependencies...'
                    sh '''
                        python3 -m venv ${VENV_DIR}
                        . ${VENV_DIR}/bin/activate
                        pip3 install --upgrade pip
                        pip3 install -r requirements.txt
                    '''
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('messaging_app') {
                    echo '🧪 Running pytest tests...'
                    sh '''
                        . ${VENV_DIR}/bin/activate
                        pytest --junitxml=report.xml
                    '''
                }
            }
        }

        stage('Publish Report') {
            steps {
                echo '📄 Publishing test results...'
                junit 'messaging_app/report.xml'
            }
        }
    }
}
