pipeline {
    agent any

    environment {
        VENV = 'venv'
    }

    stages {
        stage('Clone repository') {
            steps {
                git credentialsId: 'github-creds', url: 'https://github.com/melhard/alx-backend-python.git', branch: 'main'
            }
        }

        stage('Set up Python environment') {
            steps {
                sh '''
                    python3 -m venv ${VENV}
                    . ${VENV}/bin/activate
                    pip install --upgrade pip
                    pip install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    . ${VENV}/bin/activate
                    pytest messaging_app/tests --junitxml=report.xml
                '''
            }
        }

        stage('Archive Test Report') {
            steps {
                junit 'report.xml'
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
